pymaemo-optify: attempt to fix MB#6686
git-svn-id: https://vcs.maemo.org/svn/pymaemo@1464 f8ba266b-2117-0410-b6ba-c3dd9a426789

diff --git a/packages/pymaemo-optify/trunk/debian/init.d/pymaemo-optify b/packages/pymaemo-optify/trunk/debian/init.d/pymaemo-optify
--- a/packages/pymaemo-optify/trunk/debian/init.d/pymaemo-optify
+++ b/packages/pymaemo-optify/trunk/debian/init.d/pymaemo-optify
@@ -10,6 +10,8 @@ fi
 mount_optify()
 {
     for d in $BIND_MOUNTS; do
+        # remove any temporary mount --move targets
+        rmdir $d.move.* 2>/dev/null
         mkdir -p $d $OPT_DIR/$d
         grep -q " $d " /proc/mounts || mount --bind $OPT_DIR/$d $d
     done
@@ -19,6 +21,12 @@ umount_optify()
 {
     for d in $BIND_MOUNTS; do
         grep -q " $d " /proc/mounts && umount $d
+        if grep -q " $d " /proc/mounts; then
+            echo "WARNING: \"$d\" could not be umounted, using mount --move" >&2
+            tmpdir=`mktemp -d $d.move.XXXXXXXXXX` || continue
+            chmod 755 $tmpdir
+            mount --move $d $tmpdir
+        fi
     done
 }
 
